# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainClockWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainClockWindow(object):
    def setupUi(self, MainClockWindow):
        MainClockWindow.setObjectName("MainClockWindow")
        MainClockWindow.resize(562, 302)
        self.centralwidget = QtWidgets.QWidget(MainClockWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 20, 491, 171))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lcdNumber = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalLayout.addWidget(self.lcdNumber)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.horizontalLayout.addWidget(self.lcdNumber_2)
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.horizontalLayout.addWidget(self.lcdNumber_3)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(40, 200, 501, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(40, 230, 491, 31))
        self.textBrowser.setObjectName("textBrowser")
        MainClockWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainClockWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 562, 21))
        self.menubar.setObjectName("menubar")
        MainClockWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainClockWindow)
        self.statusbar.setObjectName("statusbar")
        MainClockWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainClockWindow)
        QtCore.QMetaObject.connectSlotsByName(MainClockWindow)

    def retranslateUi(self, MainClockWindow):
        _translate = QtCore.QCoreApplication.translate
        MainClockWindow.setWindowTitle(_translate("MainClockWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainClockWindow = QtWidgets.QMainWindow()
    ui = Ui_MainClockWindow()
    ui.setupUi(MainClockWindow)
    MainClockWindow.show()
    sys.exit(app.exec_())
