# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RecordingWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RecordingWindow(object):
    def setupUi(self, RecordingWindow):
        RecordingWindow.setObjectName("RecordingWindow")
        RecordingWindow.resize(562, 302)
        self.centralwidget = QtWidgets.QWidget(RecordingWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 121, 231))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(140, 10, 401, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        RecordingWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RecordingWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 562, 21))
        self.menubar.setObjectName("menubar")
        RecordingWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RecordingWindow)
        self.statusbar.setObjectName("statusbar")
        RecordingWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RecordingWindow)
        QtCore.QMetaObject.connectSlotsByName(RecordingWindow)

    def retranslateUi(self, RecordingWindow):
        _translate = QtCore.QCoreApplication.translate
        RecordingWindow.setWindowTitle(_translate("RecordingWindow", "MainWindow"))
        self.pushButton.setText(_translate("RecordingWindow", "Push Here to Talk"))
        self.textBrowser.setHtml(_translate("RecordingWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">SAMPLE TEXT:</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RecordingWindow = QtWidgets.QMainWindow()
    ui = Ui_RecordingWindow()
    ui.setupUi(RecordingWindow)
    RecordingWindow.show()
    sys.exit(app.exec_())
